services:
  ai_chatbot:
    build: 
      context: ./ai_chatbot/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./ai_chatbot/.env
    networks:
      - app-network

  server:
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    networks:
      - app-network

  postgres:
    build:
      context: ./database/
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/01-init.sql
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge